= Cow - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:toclevels: 3
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-T09-1/main

By: `Team T09-1`      Since: `Aug 2018`      Licence: `MIT`

== Introduction

Cow is an application for those who prefer to use a desktop app for
managing tasks and contacts. It is optimized for those who prefer to
work with a Command Line Interface (CLI) while still having the benefits
of a Graphical User Interface (GUI). If you can type fast, Cow can
get your contact and task management done faster than traditional GUI
apps.

== Quick Start

1.  Ensure you have JRE 9 or later installed.
2.  Download the `.jar`.
3.  Place it in the folder where you want the data files to be stored.
4.  Type in a command and press `Enter` to execute it. For a start, type
`help` and press `Enter` to see the help text.

== Features

**Command Format**

* Words in `UPPER_CASE` are the parameters to be supplied by the user
e.g. in `add n/NAME`, `NAME` is a parameter which can be used as
`add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used
as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…` after them can be used multiple times including zero
times e.g. `[t/TAG]...` can be used as
`\` (i.e. 0 times),`t/friend`,`t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies
`n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.

=== Viewing help: `help`

Format: `help`

=== Contacts

==== View all contacts: `contacts list`

Format: `contacts view`

==== Add contact: `contacts add`

Format: `contacts add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]…`

==== Edit contact: `contacts edit`

Format:
`contacts edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]…`

==== Find contact: `contacts find`

Format: `contacts find KEYWORD [MORE_KEYWORDS]`

==== Delete contact: `contacts delete`

Format: `contacts delete INDEX`

==== Assign tasks to contact: `contacts assign`

Format: `contacts assign c/CONTACT_INDEX k/TASK_INDEX`

==== Unassign tasks from contact: `contacts unassign`

Format: `contacts unassign c/CONTACT_INDEX... (k/TASK_INDEX...|*)`

If `*` is provided as the argument for TASK_INDEX, unassign all tasks
from the contacts specified.

==== Show tasks assigned to contact:

Format: `contacts assigned CONTACT_ID`

This will display all tasks assigned to the contact in the tasks pane.

=== Tasks

Format for entering dates is YYYYMMDD. Format for entering times is HHMM
in 24-hour time. (All commands from AB4 but prepend `tasks`)

==== View all tasks: `tasks list`

Format: `tasks list`

==== Add task: `tasks add`

Format:
`tasks add n/TASK_NAME sd/START_DATE st/START_TIME ed/END_DATE et/END_TIME [t/TAG]…`

==== Edit task: `tasks edit`

Format:
`tasks edit INDEX [n/TASK_NAME] [sd/START_DATE st/START_TIME ed/END_DATE et/END_TIME] [t/TAG]…`

==== Search for task: `tasks find`

Finds tasks whose names contain any of the given keywords. + Format:
`tasks find KEYWORD [MORE_KEYWORDS]`
****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match
`Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Tasks matching at least one keyword will be returned (i.e. `OR`
search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****
==== Delete task: `tasks delete`

Format: `tasks delete INDEX1 [INDEX2] [INDEX3] ...`

Delete all tasks corresponding to the indices provided.

==== Delete all tasks: `tasks delete all`

Format: `tasks delete all`

Delete all tasks that are shown in the list.

==== Assign person to task: `tasks assign`

Format: `tasks assign k/TASK_INDEX c/CONTACT_INDEX`

==== Unassign person from tasks: `tasks unassign`

Format: `tasks unassign k/TASK_INDEX (c/CONTACT_INDEX...|*)`

If `*` is provided as the argument for CONTACT_INDEX, all contacts will
be unassigned.

==== Show full details of a task: `tasks assigned`

Format: `tasks assigned TASK_ID`

This will display the contacts assigned to the task in the contacts
pane.

==== Display

=== Calendar

Format for entering year is YYYY.
Format for entering month is MM.
Format for entering dates is YYYYMMDD.

==== View calendar for tasks due within given year and month: `calendars show`

Format: `calendars show y/YEAR m/MONTH`

==== List tasks for a specific day: `calendars list`

Format: `calendars list ed/END_DATE`

==== Share calendar: `calendars share`

Format: `calendars share CONTACT_INDEX`

=== Global

==== Undo previous command `undo`

Format: `undo`

==== Redo previously undone command `redo`

Format: `redo`

==== Exiting the program: `exit`

Format: `exit`

==== Saving data

Data is saved in the hard disk automatically after any command that
changes the data. There is no need to save manually.
